### User List (/api/user/list)

GET http://localhost/api/user/list
Cookie: whtoken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDYzOTMyMTIsImV4cCI6MTU3NzkyOTIxMiwianRpIjoiNzkzYmJlM2JkZDIzYWU0ODRiNGFjYjM3YzEzYTBhMjUiLCJ1c2VyX2lkeCI6IjEiLCJ1c2VyX2lkIjoiYzJtIiwidXNlcl9sYW5nIjoiRU4iLCJ1c2VyX3JvbGVfaWR4IjoiMSJ9.9DLMKvRkoKcM2I8v8kB4L32k3AFf7Wwtiz8Ybic3evk; path=/; domain=localhost; Expires=Tue, 19 Jan 2038 03:14:07 GMT;

### Team Update (/api/team/{team_idx}/update)

POST http://localhost/api/team/13/update
Cookie: whtoken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDYzOTMyMTIsImV4cCI6MTU3NzkyOTIxMiwianRpIjoiNzkzYmJlM2JkZDIzYWU0ODRiNGFjYjM3YzEzYTBhMjUiLCJ1c2VyX2lkeCI6IjEiLCJ1c2VyX2lkIjoiYzJtIiwidXNlcl9sYW5nIjoiRU4iLCJ1c2VyX3JvbGVfaWR4IjoiMSJ9.9DLMKvRkoKcM2I8v8kB4L32k3AFf7Wwtiz8Ybic3evk; path=/; domain=localhost; Expires=Tue, 19 Jan 2038 03:14:07 GMT;
Content-Type: application/x-www-form-urlencoded

column=team_name
&old_val=qqwweerr
&new_val=abcde

###